<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Residential Products
            [
                'name' => 'Home Basic',
                'code' => 'RES-BASIC',
                'description' => 'Entry-level internet package ideal for light browsing and email.',
                'setup_fee' => 50.00,
                'bandwidth' => 10,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'copper',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.0,
                'is_featured' => false,
                'category_id' => 1,
            ],
            [
                'name' => 'Home Standard',
                'code' => 'RES-STD',
                'description' => 'Balanced internet package for families with multiple devices.',
                'setup_fee' => 75.00,
                'bandwidth' => 50,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'copper',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.3,
                'is_featured' => true,
                'category_id' => 1,
            ],
            [
                'name' => 'Home Premium',
                'code' => 'RES-PREM',
                'description' => 'High-speed internet for streaming, gaming, and heavy internet usage.',
                'setup_fee' => 100.00,
                'bandwidth' => 100,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'copper',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.5,
                'is_featured' => false,
                'category_id' => 1,
            ],

            // Small Business Products
            [
                'name' => 'Business Starter',
                'code' => 'BIZ-START',
                'description' => 'Basic internet solution for small offices and startups.',
                'setup_fee' => 150.00,
                'bandwidth' => 50,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'copper',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.5,
                'is_featured' => false,
                'category_id' => 2,
            ],
            [
                'name' => 'Business Pro',
                'code' => 'BIZ-PRO',
                'description' => 'Reliable internet solution for growing businesses with multiple employees.',
                'setup_fee' => 200.00,
                'bandwidth' => 100,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'copper',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.7,
                'is_featured' => true,
                'category_id' => 2,
            ],
            [
                'name' => 'Business Elite',
                'code' => 'BIZ-ELITE',
                'description' => 'Premium internet solution for businesses requiring consistent performance.',
                'setup_fee' => 300.00,
                'bandwidth' => 200,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.8,
                'is_featured' => false,
                'category_id' => 2,
            ],

            // Enterprise Products
            [
                'name' => 'Enterprise Basic',
                'code' => 'ENT-BASIC',
                'description' => 'Entry-level enterprise solution with dedicated support.',
                'setup_fee' => 500.00,
                'bandwidth' => 100,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 24,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.9,
                'is_featured' => false,
                'category_id' => 3,
            ],
            [
                'name' => 'Enterprise Plus',
                'code' => 'ENT-PLUS',
                'description' => 'Comprehensive enterprise solution for medium to large businesses.',
                'setup_fee' => 750.00,
                'bandwidth' => 500,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 24,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.95,
                'is_featured' => true,
                'category_id' => 3,
            ],
            [
                'name' => 'Enterprise Ultimate',
                'code' => 'ENT-ULT',
                'description' => 'Premium enterprise solution with the highest performance guarantees.',
                'setup_fee' => 1000.00,
                'bandwidth' => 1,
                'bandwidth_type' => 'gbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 24,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.99,
                'is_featured' => false,
                'category_id' => 3,
            ],

            // Fiber Optic Products
            [
                'name' => 'Fiber 100',
                'code' => 'FIB-100',
                'description' => 'Entry-level fiber optic connection with symmetric speeds.',
                'setup_fee' => 200.00,
                'bandwidth' => 100,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.7,
                'is_featured' => false,
                'category_id' => 4,
            ],
            [
                'name' => 'Fiber 500',
                'code' => 'FIB-500',
                'description' => 'Mid-range fiber optic connection ideal for demanding households.',
                'setup_fee' => 300.00,
                'bandwidth' => 500,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.8,
                'is_featured' => true,
                'category_id' => 4,
            ],
            [
                'name' => 'Fiber Gigabit',
                'code' => 'FIB-GIG',
                'description' => 'Premium fiber optic connection with gigabit speeds.',
                'setup_fee' => 400.00,
                'bandwidth' => 1,
                'bandwidth_type' => 'gbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.9,
                'is_featured' => false,
                'category_id' => 4,
            ],

            // Wireless Products
            [
                'name' => 'Wireless Basic',
                'code' => 'WIR-BASIC',
                'description' => 'Entry-level wireless internet solution for areas without wired infrastructure.',
                'setup_fee' => 100.00,
                'bandwidth' => 10,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'wireless',
                'minimum_contract_months' => 6,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 98.0,
                'is_featured' => false,
                'category_id' => 5,
            ],
            [
                'name' => 'Wireless Plus',
                'code' => 'WIR-PLUS',
                'description' => 'Enhanced wireless internet with broader coverage and faster speeds.',
                'setup_fee' => 150.00,
                'bandwidth' => 25,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'wireless',
                'minimum_contract_months' => 6,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 98.5,
                'is_featured' => true,
                'category_id' => 5,
            ],
            [
                'name' => 'Wireless Pro',
                'code' => 'WIR-PRO',
                'description' => 'Professional wireless internet solution for businesses in remote locations.',
                'setup_fee' => 250.00,
                'bandwidth' => 50,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'wireless',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.0,
                'is_featured' => false,
                'category_id' => 5,
            ],

            // Dedicated Line Products
            [
                'name' => 'Dedicated 50',
                'code' => 'DED-50',
                'description' => 'Entry-level dedicated connection with guaranteed bandwidth.',
                'setup_fee' => 500.00,
                'bandwidth' => 50,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 24,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.9,
                'is_featured' => false,
                'category_id' => 6,
            ],
            [
                'name' => 'Dedicated 100',
                'code' => 'DED-100',
                'description' => 'Mid-range dedicated connection for businesses requiring consistent performance.',
                'setup_fee' => 750.00,
                'bandwidth' => 100,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 24,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.95,
                'is_featured' => true,
                'category_id' => 6,
            ],
            [
                'name' => 'Dedicated 500',
                'code' => 'DED-500',
                'description' => 'Premium dedicated connection with high bandwidth and SLA guarantees.',
                'setup_fee' => 1500.00,
                'bandwidth' => 500,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 24,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.99,
                'is_featured' => false,
                'category_id' => 6,
            ],

            // Bundled Services Products
            [
                'name' => 'Internet + Voice Basic',
                'code' => 'BUN-IV-BASIC',
                'description' => 'Combined internet and VoIP package for small households.',
                'setup_fee' => 150.00,
                'bandwidth' => 25,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'copper',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.0,
                'is_featured' => false,
                'category_id' => 7,
            ],
            [
                'name' => 'Internet + Security Standard',
                'code' => 'BUN-IS-STD',
                'description' => 'Internet with advanced security features for home and small office.',
                'setup_fee' => 200.00,
                'bandwidth' => 50,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'copper',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.5,
                'is_featured' => true,
                'category_id' => 7,
            ],
            [
                'name' => 'Complete Office Bundle',
                'code' => 'BUN-OFFICE',
                'description' => 'Comprehensive package with internet, VoIP, security, and cloud storage.',
                'setup_fee' => 350.00,
                'bandwidth' => 100,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 24,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.7,
                'is_featured' => false,
                'category_id' => 7,
            ],

            // Special Promotions Products
            [
                'name' => 'New Customer Special',
                'code' => 'PROMO-NEW',
                'description' => 'Limited-time offer for new customers with reduced setup fees.',
                'setup_fee' => 25.00,
                'bandwidth' => 50,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'copper',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.0,
                'is_featured' => true,
                'category_id' => 8,
            ],
            [
                'name' => 'Summer Fiber Promotion',
                'code' => 'PROMO-SUMMER',
                'description' => 'Special summer offer for fiber connections with first month free.',
                'setup_fee' => 100.00,
                'bandwidth' => 100,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 12,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.5,
                'is_featured' => true,
                'category_id' => 8,
            ],
            [
                'name' => 'Business Upgrade Special',
                'code' => 'PROMO-BIZ-UPG',
                'description' => 'Promotional offer for businesses upgrading their existing services.',
                'setup_fee' => 0.00,
                'bandwidth' => 200,
                'bandwidth_type' => 'mbps',
                'connection_type' => 'fiber',
                'minimum_contract_months' => 24,
                'is_recurring' => true,
                'is_active' => true,
                'uptime_guarantee' => 99.7,
                'is_featured' => false,
                'category_id' => 8,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('Products seeded successfully!');
    }
}
